//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleSignalR.Contexto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPropostaComercial
    {
        public long ID { get; set; }
        public long IDUndSrv { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public long IDContratante { get; set; }
        public long IDCategoria { get; set; }
        public short IDTabelaPreco { get; set; }
        public decimal ValorProposta { get; set; }
        public Nullable<long> IDAgenteNegocios { get; set; }
        public Nullable<System.DateTime> DataHoraAtualizacaoPreco { get; set; }
        public Nullable<long> IDArea { get; set; }
        public Nullable<long> IDAbrangencia { get; set; }
        public Nullable<long> IDSituacao { get; set; }
        public Nullable<System.DateTime> DataHoraInclusao { get; set; }
        public Nullable<long> IDOperadorInclusao { get; set; }
        public Nullable<System.DateTime> DataHoraUltAlteracao { get; set; }
        public Nullable<long> IDOperadorUltAlteracao { get; set; }
        public Nullable<System.DateTime> DataHoraAprovacao { get; set; }
        public Nullable<long> IDOperadorAprovacao { get; set; }
        public Nullable<System.DateTime> DataHoraCancelamento { get; set; }
        public Nullable<long> IDOperadorCancelamento { get; set; }
        public Nullable<System.DateTime> DataHoraConclusao { get; set; }
        public Nullable<long> IDOperadorConclusao { get; set; }
        public Nullable<int> DiaVencimentoParcela { get; set; }
        public decimal ValorEntrada { get; set; }
        public Nullable<System.DateTime> DataValidadeProposta { get; set; }
        public Nullable<System.DateTime> DataValidadePreco { get; set; }
        public string ObservacoesPagamento { get; set; }
        public string ObservacoesExecucao { get; set; }
        public string ObservacoesGerais { get; set; }
        public Nullable<long> IDResponsavelContratante { get; set; }
        public Nullable<short> IDTipoVinculo { get; set; }
        public Nullable<long> IDContratoOriginal { get; set; }
        public Nullable<decimal> PercentualRenovacao { get; set; }
        public Nullable<int> IDMotivoRejeicao { get; set; }
        public string ObservacaoRejeicao { get; set; }
        public Nullable<System.DateTime> DataHoraRejeicao { get; set; }
        public Nullable<long> IDOperadorRejeicao { get; set; }
        public Nullable<long> IDUnidadeExecucao { get; set; }
        public Nullable<long> IDAgenda { get; set; }
        public Nullable<short> TipoExecucao { get; set; }
        public Nullable<short> TipoEnderecoExecucao { get; set; }
        public string EnderecoExecucao { get; set; }
        public Nullable<long> IDRegionalAdministrador { get; set; }
        public bool AdministracaoPropria { get; set; }
        public Nullable<long> IDTipoDocumentoCobranca { get; set; }
        public Nullable<long> IDTipoDocumentoFaturamento { get; set; }
        public short IDSistemaOrigem { get; set; }
    }
}
