//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleSignalR.Contexto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServico
    {
        public long ID { get; set; }
        public string CodigoInterno { get; set; }
        public string Codigo { get; set; }
        public string NMServico { get; set; }
        public long IDArea { get; set; }
        public int IDTipo { get; set; }
        public int IDTipoPreco { get; set; }
        public Nullable<int> IDModeloContrato { get; set; }
        public Nullable<int> IDModeloPropostaTecnica { get; set; }
        public string DescricaoDetalhada { get; set; }
        public Nullable<bool> PermiteAtendimento { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> InformarFuncionariosAmostra { get; set; }
        public Nullable<bool> tagResposavelTecnico { get; set; }
    }
}
