//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleSignalR.Contexto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidServ
    {
        public UnidServ()
        {
            this.Pessoa = new HashSet<Pessoa>();
        }
    
        public string CDUnidServ { get; set; }
        public string NMUnidServ { get; set; }
        public string IdZeus { get; set; }
        public string Entd { get; set; }
        public bool Mtrz { get; set; }
        public bool MultUnd { get; set; }
    
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}
