//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleSignalR.Contexto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwServicoClassificado
    {
        public long ID { get; set; }
        public string NomeServico { get; set; }
        public string CodigoInterno { get; set; }
        public Nullable<long> CodigoInteiro { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string UltimoNivel { get; set; }
        public Nullable<long> UltimoNivelInteiro { get; set; }
        public string Pai { get; set; }
        public Nullable<long> PaiInteiro { get; set; }
        public int IDTipo { get; set; }
        public int IDTipoPreco { get; set; }
    }
}
